blank_issues_enabled: false
contact_links:
  - name: 游닄 Documentaci칩n
    url: https://github.com/soker90/cafe/blob/master/README.md
    about: Lee la documentaci칩n completa del proyecto
  - name: 游깷 Ver Cat치logo Web
    url: https://soker90.github.io/cafe/
    about: Ve el cat치logo web con todos los caf칠s